services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    environment:
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-pass}
      - DB_NAME=${DB_NAME:-payments-api}
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=payments-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  postgres-data: